# Generated by Django 5.2 on 2025-04-10 14:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibe', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vibe',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_vibes', to=settings.AUTH_USER_MODEL),
        ),
    ]
